/** Frozen full baseline SQL migrations, independent of the new migration loader; no legacy runtime imports. */
export const historicalRaffleStatements = [
  "CREATE TABLE `rolls` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`roll` integer NOT NULL,\n\t`winning_number` integer NOT NULL,\n\t`distance` integer NOT NULL,\n\t`is_winner` integer NOT NULL,\n\t`rolled_at` text NOT NULL\n)",
  "CREATE INDEX `idx_rolls_user_id` ON `rolls`(`user_id`)",
  "CREATE INDEX `idx_rolls_user_distance` ON `rolls`(`user_id`, `distance`) WHERE `is_winner` = 0",
  "CREATE VIEW `raffle_leaderboard` AS\nWITH \nuser_aggregates AS (\n  SELECT \n    `user_id`,\n    COUNT(*) as `total_rolls`,\n    CAST(SUM(`is_winner`) AS INTEGER) as `total_wins`,\n    MAX(`rolled_at`) as `last_rolled_at`\n  FROM `rolls`\n  GROUP BY `user_id`\n),\nclosest AS (\n  SELECT DISTINCT \n    `user_id`,\n    FIRST_VALUE(`distance`) OVER w as `closest_distance`,\n    FIRST_VALUE(`roll`) OVER w as `closest_roll`,\n    FIRST_VALUE(`winning_number`) OVER w as `closest_winning_number`\n  FROM `rolls`\n  WHERE `is_winner` = 0\n  WINDOW w AS (PARTITION BY `user_id` ORDER BY `distance` ASC)\n),\nlatest AS (\n  SELECT DISTINCT\n    `user_id`,\n    FIRST_VALUE(`display_name`) OVER (PARTITION BY `user_id` ORDER BY `rolled_at` DESC) as `display_name`\n  FROM `rolls`\n)\nSELECT \n  a.`user_id`,\n  l.`display_name`,\n  a.`total_rolls`,\n  a.`total_wins`,\n  c.`closest_distance`,\n  c.`closest_roll`,\n  c.`closest_winning_number`,\n  a.`last_rolled_at`\nFROM user_aggregates a\nLEFT JOIN latest l ON a.`user_id` = l.`user_id`\nLEFT JOIN closest c ON a.`user_id` = c.`user_id`\nORDER BY a.`total_rolls` DESC",
  "DROP VIEW `raffle_leaderboard`",
  "PRAGMA foreign_keys=OFF",
  'CREATE TABLE `__new_rolls` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`roll` integer NOT NULL,\n\t`winning_number` integer NOT NULL,\n\t`distance` integer NOT NULL,\n\t`is_winner` integer NOT NULL,\n\t`is_new_record` integer NOT NULL,\n\t`rolled_at` text NOT NULL,\n\tCONSTRAINT "rolls_user_id_nonempty" CHECK(length(`user_id`) > 0),\n\tCONSTRAINT "rolls_display_name_nonempty" CHECK(length(`display_name`) > 0),\n\tCONSTRAINT "rolls_roll_range" CHECK(`roll` between 1 and 10000),\n\tCONSTRAINT "rolls_winning_number_range" CHECK(`winning_number` between 1 and 10000),\n\tCONSTRAINT "rolls_distance_invariant" CHECK(`distance` = abs(`roll` - `winning_number`)),\n\tCONSTRAINT "rolls_winner_invariant" CHECK(`is_winner` = (`distance` = 0))\n)',
  "INSERT INTO `__new_rolls` (\n\t`id`, `user_id`, `display_name`, `roll`, `winning_number`, `distance`, `is_winner`, `is_new_record`, `rolled_at`\n)\nSELECT\n\tcurrent.`id`, current.`user_id`, current.`display_name`, current.`roll`, current.`winning_number`,\n\tcurrent.`distance`, current.`is_winner`,\n\tCASE WHEN current.`distance` > 0 AND NOT EXISTS (\n\t\tSELECT 1 FROM `rolls` prior\n\t\tWHERE prior.rowid < current.rowid\n\t\t\tAND prior.`distance` > 0\n\t\t\tAND prior.`distance` <= current.`distance`\n\t) THEN 1 ELSE 0 END,\n\tcurrent.`rolled_at`\nFROM `rolls` current",
  "DROP TABLE `rolls`",
  "ALTER TABLE `__new_rolls` RENAME TO `rolls`",
  "CREATE INDEX `idx_rolls_user_id` ON `rolls`(`user_id`)",
  "CREATE INDEX `idx_rolls_user_distance` ON `rolls`(`user_id`, `distance`)",
  "CREATE VIEW `raffle_leaderboard` AS\nWITH\nuser_aggregates AS (\n  SELECT `user_id`, COUNT(*) as `total_rolls`, CAST(SUM(`is_winner`) AS INTEGER) as `total_wins`, MAX(`rolled_at`) as `last_rolled_at`\n  FROM `rolls` GROUP BY `user_id`\n),\nclosest AS (\n  SELECT DISTINCT `user_id`, FIRST_VALUE(`distance`) OVER w as `closest_distance`, FIRST_VALUE(`roll`) OVER w as `closest_roll`, FIRST_VALUE(`winning_number`) OVER w as `closest_winning_number`\n  FROM `rolls` WHERE `is_winner` = 0 WINDOW w AS (PARTITION BY `user_id` ORDER BY `distance` ASC)\n),\nlatest AS (\n  SELECT DISTINCT `user_id`, FIRST_VALUE(`display_name`) OVER (PARTITION BY `user_id` ORDER BY `rolled_at` DESC) as `display_name`\n  FROM `rolls`\n)\nSELECT a.`user_id`, l.`display_name`, a.`total_rolls`, a.`total_wins`, c.`closest_distance`, c.`closest_roll`, c.`closest_winning_number`, a.`last_rolled_at`\nFROM user_aggregates a\nLEFT JOIN latest l ON a.`user_id` = l.`user_id`\nLEFT JOIN closest c ON a.`user_id` = c.`user_id`\nORDER BY a.`total_rolls` DESC",
  "PRAGMA foreign_keys=ON",
];
