/** Baseline HTTP validation snapshots captured from the pinned read-only 4.3.5 parser oracle. */
export const httpValidationGoldenCases = [
  {
    method: "GET",
    path: "/api/queue?limit=1.5&unknown=x&another=y",
    error: "Invalid query parameters",
    details: [
      {
        expected: "int",
        format: "safeint",
        code: "invalid_type",
        path: ["limit"],
        message: "Invalid input: expected int, received number",
      },
      {
        code: "unrecognized_keys",
        keys: ["unknown", "another"],
        path: [],
        message: 'Unrecognized keys: "unknown", "another"',
      },
    ],
  },
  {
    method: "GET",
    path: "/api/queue?limit=1&limit=2",
    error: "Invalid query parameters",
    details: [
      {
        expected: "number",
        code: "invalid_type",
        received: "NaN",
        path: ["limit"],
        message: "Invalid input: expected number, received NaN",
      },
    ],
  },
  {
    method: "GET",
    path: "/api/queue?limit=NaN",
    error: "Invalid query parameters",
    details: [
      {
        expected: "number",
        code: "invalid_type",
        received: "NaN",
        path: ["limit"],
        message: "Invalid input: expected number, received NaN",
      },
    ],
  },
  {
    method: "GET",
    path: "/api/queue?limit=Infinity",
    error: "Invalid query parameters",
    details: [
      {
        expected: "number",
        code: "invalid_type",
        received: "Infinity",
        path: ["limit"],
        message: "Invalid input: expected number, received number",
      },
    ],
  },
  {
    method: "GET",
    path: "/api/queue?limit=-1",
    error: "Invalid query parameters",
    details: [
      {
        origin: "number",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["limit"],
        message: "Too small: expected number to be >=1",
      },
    ],
  },
  {
    method: "GET",
    path: "/api/queue?limit=101",
    error: "Invalid query parameters",
    details: [
      {
        origin: "number",
        code: "too_big",
        maximum: 100,
        inclusive: true,
        path: ["limit"],
        message: "Too big: expected number to be <=100",
      },
    ],
  },
  {
    method: "GET",
    path: "/api/queue?limit=",
    error: "Invalid query parameters",
    details: [
      {
        origin: "number",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["limit"],
        message: "Too small: expected number to be >=1",
      },
    ],
  },
  {
    method: "GET",
    path: "/api/stats/top-requesters?nonce=1",
    error: "Invalid query parameters",
    details: [
      {
        code: "unrecognized_keys",
        keys: ["nonce"],
        path: [],
        message: 'Unrecognized key: "nonce"',
      },
    ],
  },
  {
    method: "GET",
    path: "/api/stats/raffle/leaderboard?sortBy=wrong&limit=0&extra=x",
    error: "Invalid query parameters",
    details: [
      {
        code: "invalid_value",
        values: ["rolls", "wins", "closest"],
        path: ["sortBy"],
        message: 'Invalid option: expected one of "rolls"|"wins"|"closest"',
      },
      {
        origin: "number",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["limit"],
        message: "Too small: expected number to be >=1",
      },
      {
        code: "unrecognized_keys",
        keys: ["extra"],
        path: [],
        message: 'Unrecognized key: "extra"',
      },
    ],
  },
  {
    method: "GET",
    path: "/api/admin/dlq?limit=101&offset=-2",
    error: "Invalid query parameters",
    details: [
      {
        origin: "number",
        code: "too_big",
        maximum: 100,
        inclusive: true,
        path: ["limit"],
        message: "Too big: expected number to be <=100",
      },
      {
        origin: "number",
        code: "too_small",
        minimum: 0,
        inclusive: true,
        path: ["offset"],
        message: "Too small: expected number to be >=0",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: {},
    error: "Invalid command payload",
    details: [
      {
        code: "invalid_union",
        errors: [],
        note: "No matching discriminator",
        discriminator: "responseType",
        path: ["responseType"],
        message: "Invalid input",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: 42,
    error: "Invalid command payload",
    details: [
      {
        code: "invalid_type",
        expected: "object",
        path: [],
        message: "Invalid input: expected object, received number",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: null,
    error: "Invalid command payload",
    details: [
      {
        code: "invalid_type",
        expected: "object",
        path: [],
        message: "Invalid input: expected object, received null",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: [],
    error: "Invalid command payload",
    details: [
      {
        code: "invalid_type",
        expected: "object",
        path: [],
        message: "Invalid input: expected object, received array",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: {
      responseType: "computed",
      name: "UPPER",
      description: "",
      category: "wrong",
      permission: "no",
    },
    error: "Invalid command payload",
    details: [
      {
        origin: "string",
        code: "invalid_format",
        format: "regex",
        pattern: "/^[a-z0-9-]+$/",
        path: ["name"],
        message: "Invalid string: must match pattern /^[a-z0-9-]+$/",
      },
      {
        origin: "string",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["description"],
        message: "Too small: expected string to have >=1 characters",
      },
      {
        code: "invalid_value",
        values: ["info", "stats", "meta", "music"],
        path: ["category"],
        message: 'Invalid option: expected one of "info"|"stats"|"meta"|"music"',
      },
      {
        code: "invalid_value",
        values: ["everyone", "vip", "moderator", "broadcaster"],
        path: ["permission"],
        message: 'Invalid option: expected one of "everyone"|"vip"|"moderator"|"broadcaster"',
      },
      {
        expected: "string",
        code: "invalid_type",
        path: ["handlerKey"],
        message: "Invalid input: expected string, received undefined",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: {
      name: "",
      description: "Valid",
      category: "info",
      permission: "everyone",
      responseType: "static",
      aliases: ["UPPER", ""],
      extra: 1,
      other: 2,
    },
    error: "Invalid command payload",
    details: [
      {
        origin: "string",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["name"],
        message: "Too small: expected string to have >=1 characters",
      },
      {
        origin: "string",
        code: "invalid_format",
        format: "regex",
        pattern: "/^[a-z0-9-]+$/",
        path: ["name"],
        message: "Invalid string: must match pattern /^[a-z0-9-]+$/",
      },
      {
        origin: "string",
        code: "invalid_format",
        format: "regex",
        pattern: "/^[a-z0-9-]+$/",
        path: ["aliases", 0],
        message: "Invalid string: must match pattern /^[a-z0-9-]+$/",
      },
      {
        origin: "string",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["aliases", 1],
        message: "Too small: expected string to have >=1 characters",
      },
      {
        origin: "string",
        code: "invalid_format",
        format: "regex",
        pattern: "/^[a-z0-9-]+$/",
        path: ["aliases", 1],
        message: "Invalid string: must match pattern /^[a-z0-9-]+$/",
      },
      {
        code: "unrecognized_keys",
        keys: ["extra", "other"],
        path: [],
        message: 'Unrecognized keys: "extra", "other"',
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: {
      name: "valid",
      description: "Valid",
      category: "info",
      permission: "everyone",
      responseType: "static",
      createdAt: "bad",
    },
    error: "Invalid command payload",
    details: [
      {
        origin: "string",
        code: "invalid_format",
        format: "datetime",
        pattern:
          "/^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$/",
        path: ["createdAt"],
        message: "Invalid ISO datetime",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: {
      name: "valid",
      description: "Valid",
      category: "info",
      permission: "everyone",
      responseType: "computed",
      handlerKey: "f",
      initialCounter: -1,
    },
    error: "Invalid command payload",
    details: [
      {
        origin: "number",
        code: "too_small",
        minimum: 0,
        inclusive: true,
        path: ["initialCounter"],
        message: "Too small: expected number to be >=0",
      },
    ],
  },
  {
    method: "POST",
    path: "/api/admin/commands",
    body: {
      name: "valid",
      description: "Valid",
      category: "info",
      permission: "everyone",
      responseType: "computed",
      handlerKey: "f",
      initialCounter: 1.5,
    },
    error: "Invalid command payload",
    details: [
      {
        expected: "int",
        format: "safeint",
        code: "invalid_type",
        path: ["initialCounter"],
        message: "Invalid input: expected int, received number",
      },
    ],
  },
  {
    method: "PATCH",
    path: "/api/admin/commands/keyboard",
    body: {},
    error: "Invalid command patch",
    details: [
      {
        code: "custom",
        path: [],
        message: "Command patch must not be empty",
      },
    ],
  },
  {
    method: "PATCH",
    path: "/api/admin/commands/keyboard",
    body: {
      enable: false,
    },
    error: "Invalid command patch",
    details: [
      {
        code: "unrecognized_keys",
        keys: ["enable"],
        path: [],
        message: 'Unrecognized key: "enable"',
      },
    ],
  },
  {
    method: "PATCH",
    path: "/api/admin/commands/keyboard",
    body: {
      description: "",
      aliases: ["UPPER"],
      enabled: "yes",
      permission: "no",
      handlerKey: 42,
    },
    error: "Invalid command patch",
    details: [
      {
        origin: "string",
        code: "too_small",
        minimum: 1,
        inclusive: true,
        path: ["description"],
        message: "Too small: expected string to have >=1 characters",
      },
      {
        code: "invalid_value",
        values: ["everyone", "vip", "moderator", "broadcaster"],
        path: ["permission"],
        message: 'Invalid option: expected one of "everyone"|"vip"|"moderator"|"broadcaster"',
      },
      {
        expected: "boolean",
        code: "invalid_type",
        path: ["enabled"],
        message: "Invalid input: expected boolean, received string",
      },
      {
        origin: "string",
        code: "invalid_format",
        format: "regex",
        pattern: "/^[a-z0-9-]+$/",
        path: ["aliases", 0],
        message: "Invalid string: must match pattern /^[a-z0-9-]+$/",
      },
      {
        expected: "string",
        code: "invalid_type",
        path: ["handlerKey"],
        message: "Invalid input: expected string, received number",
      },
    ],
  },
  {
    method: "PATCH",
    path: "/api/admin/commands/keyboard",
    body: {
      description:
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      aliases: [
        "alias-0",
        "alias-1",
        "alias-2",
        "alias-3",
        "alias-4",
        "alias-5",
        "alias-6",
        "alias-7",
        "alias-8",
        "alias-9",
        "alias-10",
        "alias-11",
        "alias-12",
        "alias-13",
        "alias-14",
        "alias-15",
        "alias-16",
        "alias-17",
        "alias-18",
        "alias-19",
        "alias-20",
      ],
    },
    error: "Invalid command patch",
    details: [
      {
        origin: "string",
        code: "too_big",
        maximum: 200,
        inclusive: true,
        path: ["description"],
        message: "Too big: expected string to have <=200 characters",
      },
      {
        origin: "array",
        code: "too_big",
        maximum: 20,
        inclusive: true,
        path: ["aliases"],
        message: "Too big: expected array to have <=20 items",
      },
    ],
  },
  {
    method: "PATCH",
    path: "/api/admin/commands/keyboard",
    body: {
      writePermission: "not-a-role",
      counterSourceName: 123,
    },
    error: "Invalid command patch",
    details: [
      {
        expected: "string",
        code: "invalid_type",
        path: ["counterSourceName"],
        message: "Invalid input: expected string, received number",
      },
      {
        code: "invalid_value",
        values: ["everyone", "vip", "moderator", "broadcaster"],
        path: ["writePermission"],
        message: 'Invalid option: expected one of "everyone"|"vip"|"moderator"|"broadcaster"',
      },
    ],
  },
  {
    method: "PATCH",
    path: "/api/admin/commands/keyboard",
    body: {
      description: null,
      category: 42,
      extra: 1,
    },
    error: "Invalid command patch",
    details: [
      {
        expected: "string",
        code: "invalid_type",
        path: ["description"],
        message: "Invalid input: expected string, received null",
      },
      {
        code: "invalid_value",
        values: ["info", "stats", "meta", "music"],
        path: ["category"],
        message: 'Invalid option: expected one of "info"|"stats"|"meta"|"music"',
      },
      {
        code: "unrecognized_keys",
        keys: ["extra"],
        path: [],
        message: 'Unrecognized key: "extra"',
      },
    ],
  },
] as const;
