import { Context, Effect, Redacted, Result, Schema } from "effect";
import { HttpServerRequest, HttpServerResponse } from "effect/unstable/http";
import { NonNegativeInt, PageSize } from "@cf-twitch/contracts/identity";
import { SongQueueLimit } from "@cf-twitch/contracts/song-queue";
import type { TwitchHttpError } from "@cf-twitch/contracts/twitch-api";
import {
  formatHttpEnumIssue,
  formatHttpNumberIssues,
  formatHttpUnknownKeys,
} from "./http-validation-issues.ts";

/** Correlation identifiers are generated by the server, never accepted from request headers. */
export class HttpRequestCorrelation extends Context.Service<
  HttpRequestCorrelation,
  { readonly requestId: string; readonly traceId: string }
>()("@cf-twitch/HttpRequestCorrelation") {}

/** Boundary rejection carries only a safe public error, not credentials or provider bodies. */
export class HttpBoundaryError extends Schema.TaggedError<HttpBoundaryError>()(
  "HttpBoundaryError",
  {
    status: Schema.Int,
    error: Schema.String,
    code: Schema.optionalKey(Schema.String),
    details: Schema.optionalKey(Schema.Json),
  },
) {}

type HttpErrorEnvelope = {
  -readonly [Key in keyof typeof TwitchHttpError.Type]: (typeof TwitchHttpError.Type)[Key];
};

/** Render expected boundary failures using the existing untagged public envelope. */
export const renderHttpBoundaryError = (
  failure: HttpBoundaryError,
): HttpServerResponse.HttpServerResponse => {
  const body: HttpErrorEnvelope = { error: failure.error };
  if (failure.code !== undefined) body.code = failure.code;
  if (failure.details !== undefined) body.details = failure.details;
  return HttpServerResponse.jsonUnsafe(body, { status: failure.status });
};

/** Web Crypto compares authentication evidence using its constant-time HMAC verification primitive. */
export const compareHttpSecret = Effect.fn("Http.compareSecret")(function* (
  provided: Redacted.Redacted<string>,
  expected: Redacted.Redacted<string>,
) {
  return yield* Effect.tryPromise({
    try: async () => {
      const encoder = new TextEncoder();
      const algorithm = { name: "HMAC", hash: "SHA-256" };
      const candidateKey = await crypto.subtle.importKey(
        "raw",
        encoder.encode(Redacted.value(provided)),
        algorithm,
        false,
        ["sign"],
      );
      const expectedKey = await crypto.subtle.importKey(
        "raw",
        encoder.encode(Redacted.value(expected)),
        algorithm,
        false,
        ["verify"],
      );
      const message = encoder.encode("CF Twitch HTTP credential verification");
      const signature = await crypto.subtle.sign("HMAC", candidateKey, message);
      return crypto.subtle.verify("HMAC", expectedKey, signature, message);
    },
    catch: () => new HttpBoundaryError({ status: 503, error: "Authentication unavailable" }),
  });
});

/** Authenticate before parsing privileged input; empty configuration always fails closed. */
export const requireHttpAdministrator = Effect.fn("Http.requireAdministrator")(function* (
  secret: Redacted.Redacted<string>,
  audience: "Admin API" | "Debug API" | "EventSub management",
) {
  if (Redacted.value(secret).length === 0)
    return yield* Effect.fail(
      new HttpBoundaryError({
        status: 503,
        error: `${audience} not configured`.replace("management not", "management is not"),
      }),
    );
  const request = yield* HttpServerRequest.HttpServerRequest;
  const authorization = request.headers["authorization"];
  if (!authorization)
    return yield* Effect.fail(
      new HttpBoundaryError({ status: 401, error: "Missing Authorization header" }),
    );
  const [scheme, token, extra] = authorization.split(" ");
  if (scheme !== "Bearer" || !token || (audience === "EventSub management" && extra !== undefined))
    return yield* Effect.fail(
      new HttpBoundaryError({
        status: 401,
        error:
          audience === "EventSub management"
            ? "Invalid Authorization header format"
            : "Invalid Authorization header format. Expected: Bearer <token>",
      }),
    );
  if (!(yield* compareHttpSecret(Redacted.make(token), secret)))
    return yield* Effect.fail(new HttpBoundaryError({ status: 403, error: "Invalid token" }));
});

/** Encode service values through their owning response schema; corrupt responses are never returned as success. */
export const encodeHttpResponse = <A>(
  schema: Schema.ConstraintCodec<A, unknown, unknown, never>,
  value: A,
  status = 200,
): Effect.Effect<HttpServerResponse.HttpServerResponse, HttpBoundaryError> =>
  HttpServerResponse.schemaJson(schema)(value, { status }).pipe(
    Effect.mapError(
      () => new HttpBoundaryError({ status: 502, error: "Invalid service response" }),
    ),
  );

/** Render only expected HTTP failures; defects and interruption stay visible to the root. */
export const handleHttpBoundary = <R>(
  effect: Effect.Effect<HttpServerResponse.HttpServerResponse, HttpBoundaryError, R>,
): Effect.Effect<HttpServerResponse.HttpServerResponse, never, R> =>
  effect.pipe(
    Effect.catchTag("HttpBoundaryError", (error) => Effect.succeed(renderHttpBoundaryError(error))),
  );

const decodePageSize = Schema.decodeEffect(PageSize);
const decodeSongQueueLimit = Schema.decodeEffect(SongQueueLimit);
const decodeOffset = Schema.decodeEffect(NonNegativeInt);
const sortSchema = Schema.Literals(["rolls", "wins", "closest"]);
const sortFromString = Schema.String.pipe(Schema.decodeTo(sortSchema));
const decodeSort = Schema.decodeEffect(sortFromString);
const leaderboardSortValues = ["rolls", "wins", "closest"] as const;

const readHttpSearchParams = Effect.fn("Http.readSearchParams")(function* () {
  const request = yield* HttpServerRequest.HttpServerRequest;
  return new URL(request.originalUrl, "https://http.internal").searchParams;
});
const readPublicLimitValue = (query: URLSearchParams): number =>
  query.getAll("limit").length > 1
    ? Number.NaN
    : query.has("limit")
      ? Number(query.get("limit"))
      : 10;
const findUnknownQueryKeys = (
  query: URLSearchParams,
  allowed: readonly string[],
): readonly string[] => [...new Set(query.keys())].filter((key) => !allowed.includes(key));
const invalidQueryParameters = (details: readonly Schema.Json[]) =>
  new HttpBoundaryError({ status: 400, error: "Invalid query parameters", details });
const decodeHttpLimit = <A>(
  decode: (input: number) => Effect.Effect<A, Schema.SchemaError>,
  value: number,
  unknownKeys: readonly string[],
): Effect.Effect<A, HttpBoundaryError> =>
  decode(value).pipe(
    Effect.mapError(() =>
      invalidQueryParameters([
        ...formatHttpNumberIssues(value, ["limit"], 1, 100),
        ...(unknownKeys.length > 0 ? [formatHttpUnknownKeys(unknownKeys)] : []),
      ]),
    ),
    Effect.filterOrFail(
      () => unknownKeys.length === 0,
      () => invalidQueryParameters([formatHttpUnknownKeys(unknownKeys)]),
    ),
  );

/** Parse the sole public limit query parameter into a branded page size. */
export const parseHttpLimitQuery = Effect.fn("Http.parseLimitQuery")(function* () {
  const query = yield* readHttpSearchParams();
  return yield* decodeHttpLimit(
    decodePageSize,
    readPublicLimitValue(query),
    findUnknownQueryKeys(query, ["limit"]),
  );
});

/** Parse public leaderboard limit and ordering query parameters. */
export const parseHttpLeaderboardQuery = Effect.fn("Http.parseLeaderboardQuery")(function* () {
  const query = yield* readHttpSearchParams();
  const limitValue = readPublicLimitValue(query);
  const sortValue = query.get("sortBy") ?? "closest";
  const unknownKeys = findUnknownQueryKeys(query, ["limit", "sortBy"]);
  const [limitResult, sortResult] = yield* Effect.all([
    decodePageSize(limitValue).pipe(Effect.result),
    decodeSort(sortValue).pipe(Effect.result),
  ]);
  const issues = [
    ...(Result.isFailure(sortResult) || query.getAll("sortBy").length > 1
      ? [formatHttpEnumIssue(leaderboardSortValues, ["sortBy"])]
      : []),
    ...(Result.isFailure(limitResult) ? formatHttpNumberIssues(limitValue, ["limit"], 1, 100) : []),
    ...(unknownKeys.length > 0 ? [formatHttpUnknownKeys(unknownKeys)] : []),
  ];
  if (Result.isFailure(limitResult) || Result.isFailure(sortResult) || issues.length > 0)
    return yield* Effect.fail(invalidQueryParameters(issues));
  return { limit: limitResult.success, sortBy: sortResult.success };
});

/** Parse administrator pagination while retaining its permissive unknown-key compatibility. */
export const parseHttpAdminPageQuery = Effect.fn("Http.parseAdminPageQuery")(function* () {
  const query = yield* readHttpSearchParams();
  const limitValue = query.has("limit") ? Number(query.get("limit")) : 50;
  const offsetValue = query.has("offset") ? Number(query.get("offset")) : 0;
  const [limitResult, offsetResult] = yield* Effect.all([
    decodePageSize(limitValue).pipe(Effect.result),
    decodeOffset(offsetValue).pipe(Effect.result),
  ]);
  const issues = [
    ...(Result.isFailure(limitResult) ? formatHttpNumberIssues(limitValue, ["limit"], 1, 100) : []),
    ...(Result.isFailure(offsetResult)
      ? formatHttpNumberIssues(offsetValue, ["offset"], 0, Number.MAX_SAFE_INTEGER)
      : []),
  ];
  if (Result.isFailure(limitResult) || Result.isFailure(offsetResult))
    return yield* Effect.fail(invalidQueryParameters(issues));
  return { limit: limitResult.success, offset: offsetResult.success };
});

/** Reject every query parameter on endpoints whose compatibility contract has no query. */
export const rejectHttpQueryParameters = Effect.fn("Http.rejectQueryParameters")(function* () {
  const query = yield* readHttpSearchParams();
  const unknownKeys = findUnknownQueryKeys(query, []);
  if (unknownKeys.length > 0)
    return yield* Effect.fail(invalidQueryParameters([formatHttpUnknownKeys(unknownKeys)]));
});

/** Parse a public song queue limit directly into its nominal service type. */
export const parseHttpSongQueueQuery = Effect.fn("Http.parseSongQueueQuery")(function* () {
  const query = yield* readHttpSearchParams();
  return yield* decodeHttpLimit(
    decodeSongQueueLimit,
    readPublicLimitValue(query),
    findUnknownQueryKeys(query, ["limit"]),
  );
});
