import { defineConfig } from "vite-plus";

export default defineConfig({
	lint: {
		plugins: ["typescript", "import", "promise"],
		jsPlugins: [
			{ name: "local", specifier: "./tools/oxlint-rules/no-dynamic-import.cjs" },
			{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
			{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
			{ name: "better-result", specifier: "./tools/oxlint/better-result-plugin.ts" },
		],
		env: {
			browser: true,
			es2024: true,
		},
		globals: {
			DurableObject: "readonly",
			DurableObjectState: "readonly",
			DurableObjectId: "readonly",
			DurableObjectNamespace: "readonly",
			DurableObjectStub: "readonly",
			DurableObjectStorage: "readonly",
			Workflow: "readonly",
			Queue: "readonly",
			AnalyticsEngineDataset: "readonly",
			VectorizeIndex: "readonly",
			Ai: "readonly",
			Fetcher: "readonly",
			ExportedHandlerQueueHandler: "readonly",
			Rpc: "readonly",
		},
		rules: {
			"no-console": "warn",
			"anti-slop/no-chained-type-assertions": "error",
			"anti-slop/no-conditional-empty-object-spread": "error",
			"anti-slop/no-known-value-widening": "error",
			"anti-slop/no-module-mocking": "error",
			"anti-slop/no-object-parameters": "error",
			"anti-slop/no-reflect-apply": "error",
			"anti-slop/no-reflect-get": "error",
			"anti-slop/no-runtime-typeof": "error",
			"anti-slop/no-unsafe-dictionary-type": "error",
			"anti-slop/no-shape-in-symbol-names": "error",
			"anti-slop/no-unknown-parameters": "error",
			"anti-slop/no-unknown-returns": "error",
			"anti-slop/no-unknown-type-aliases": "error",
			"anti-slop/no-widen-then-assert": "error",
			"anti-slop/require-safety-comment-for-type-assertion": "error",
			"better-result/no-result-type-alias": "error",
			"typescript/no-explicit-any": "error",
			"typescript/no-non-null-assertion": "error",
			"import/no-cycle": "error",
			"local/no-dynamic-import": "error",
			"vite-plus/prefer-vite-plus-imports": "error",
		},
		overrides: [
			{
				files: ["**/logger.ts"],
				rules: {
					"no-console": "off",
				},
			},
		],
		ignorePatterns: [
			"node_modules",
			"dist",
			"*.d.ts",
			"opensrc",
			".agent/**",
			".agents/**",
			".claude/**",
			".codex/**",
			".continue/**",
			".cursor/**",
			".gemini/**",
			".opencode/**",
			".pi",
			".pi/**",
			".roo/**",
			".windsurf/**",
			"**/.agents/**",
			"tools/oxlint/anti-slop/**",
			"skills-lock.json",
			"**/drizzle/**/migrations.js",
		],
		// tsgolint currently mis-types TC39-decorated Durable Object classes.
		// Keep `tsc --noEmit` as the project type-check until that limitation is fixed.
		options: { typeAware: false, typeCheck: false },
	},
	test: {
		projects: ["apps/*"],
	},
	fmt: {
		useTabs: true,
		tabWidth: 2,
		printWidth: 100,
		semi: true,
		singleQuote: false,
		trailingComma: "all",
		bracketSpacing: true,
		arrowParens: "always",
		endOfLine: "lf",
		experimentalSortImports: {
			order: "asc",
			ignoreCase: true,
			newlinesBetween: true,
			groups: [["builtin", "external"], ["internal"], ["parent", "sibling", "index"], ["type"]],
			internalPattern: ["~/**", "@/**"],
		},
		ignorePatterns: [
			"node_modules",
			"dist",
			"*.d.ts",
			"opensrc",
			".agent/**",
			".agents/**",
			".claude/**",
			".codex/**",
			".continue/**",
			".cursor/**",
			".gemini/**",
			".opencode/**",
			".pi",
			".pi/**",
			".roo/**",
			".windsurf/**",
			"**/.agents/**",
			"tools/oxlint/anti-slop/**",
			"skills-lock.json",
			"pnpm-lock.yaml",
		],
	},
});
